# Power Rankings Visualiation - Checking for disparities between actual table & rankings

In [1]:
#libs
from IPython.display import display, HTML
import pandas as pd

In [2]:
power_ranking_df = pd.read_csv(r'../data/power_rankings_2526.csv')
prem_table_df = pd.read_csv(r'../data/summary_table2526.csv')

display(HTML(f"""
<div style="display: flex; gap: 50px;">
    <div>{power_ranking_df.to_html(index=False)}</div>
    <div>{prem_table_df.to_html(index=False)}</div>
</div>
"""))

As you can see, there actually are some disparities between the actual premier league table and simulated ELO.